version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for a static HTML site"
  build:
    commands:
      - echo "Building HTML site (no compilation necessary)"
  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - '/*'
  base-directory: .
